use super::{DialogueLine, DialogueScene};
use crate::dialogue::Choice;

pub fn create_chapter2() -> DialogueScene {
    DialogueScene {
        scene_id: "chapter2".to_string(),
        background: Some("oksang".to_string()),
        lines: vec![
            DialogueLine {
                speaker: "나레이션".to_string(),
                text: "다음날 오후, 옥상".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("oksang".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["성헌".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "하 대체 여기서 뭘 찾겠다는거야?".to_string(),
                character_emotion: Some("hwana".to_string()),//찡그리는 표정 하나 만들기
                background: Some("oksang".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "천천히 둘러보자, 체육관에서도 꽤 눈에 띄는 곳에 있었잖아".to_string(),
                character_emotion: Some("def".to_string()),//찡그리는 표정 하나 만들기
                background: Some("oksang".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "그니깐 내 말이 그거야.. 우리 벌써 여기서 20분째 둘러보고 있었잖아..".to_string(),
                character_emotion: Some("hansim".to_string()),//찡그리는 표정 하나 만들기
                background: Some("oksang".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "그렇긴 한데.. 그래도 옥상에 무조건 있을거야..".to_string(),
                character_emotion: Some("def".to_string()),//찡그리는 표정 하나 만들기
                background: Some("oksang".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "어.. 잠만 여기 문 뒤에 이건가?".to_string(),
                character_emotion: Some("def".to_string()),//하나 표정 추가
                background: Some("oksang".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "어 그러게? 바로 앞에 있었네?".to_string(),
                character_emotion: Some("def".to_string()),//찡그리는 표정 하나 만들기
                background: Some("oksang".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "하 진짜 말도안돼, 바로 앞에 두고 삽질했네..".to_string(),
                character_emotion: Some("hwana".to_string()),//찡그리는 표정 하나 만들기
                background: Some("oksang".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "그러게 설마 문 닫힌거에 가려졌을 줄은 상상을 못했네....그나저나 이건 별자린가.?".to_string(),
                character_emotion: Some("def".to_string()),//찡그리는 표정 하나 만들기
                background: Some("oksang".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "...응 카시오페이아야.".to_string(),
                character_emotion: Some("hansim".to_string()),//찡그리는 표정 하나 만들기
                background: Some("oksang".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "뭐야? 하나 너 별자리 알고있어?".to_string(),
                character_emotion: Some("def".to_string()),//찡그리는 표정 하나 만들기
                background: Some("oksang".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "그냥 뭐 적당히? 예전에 어릴 때 잠깐 취미로 찾아봤어.".to_string(),
                character_emotion: Some("def".to_string()),//찡그리는 표정 하나 만들기
                background: Some("oksang".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "진짜 의외긴 하다..".to_string(),
                character_emotion: Some("def".to_string()),//찡그리는 표정 하나 만들기
                background: Some("oksang".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "뭐? 이게 진짜 죽을래?".to_string(),
                character_emotion: Some("hwana".to_string()),//찡그리는 표정 하나 만들기
                background: Some("oksang".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "암튼, 뭐 별이란게 참 보다보면 아무생각도 안할 수 있더라고.. 그래서 좀 좋아했었어.".to_string(),
                character_emotion: Some("hansim".to_string()),//찡그리는 표정 하나 만들기
                background: Some("oksang".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "했었어? 과거형이네 지금은 왜 안좋아해?".to_string(),
                character_emotion: Some("def".to_string()),//찡그리는 표정 하나 만들기
                background: Some("oksang".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "됐어, 아무생각 안하고 있을 시간이 어딨다고.. 바빠죽겠는데 방해만 되잖아.".to_string(),
                character_emotion: Some("musi".to_string()),
                background: Some("oksang".to_string()), 
                choices: Some(vec![  // 선택지 추가
                    Choice {
                        text: "너무 부담가지지 마. 취미 하나쯤 괜찮을거야.".to_string(),
                        next_scene_id: None,  // 같은 씬 내에서 진행
                        next_line_index: Some(17),  // 다음 라인으로 자동 진행
                        choice_id: "".to_string(),
                        affection_changes: None,
                    },
                    Choice {
                        text: "그래? 그래도 휴대폰 하루종일 하는 것 보단 별자리 보는거면 괜찮지 않나?".to_string(),
                        next_scene_id: None,  // chapter1 씬으로 이동
                        next_line_index: Some(18),  // 무시됨 (다른 씬으로 이동하므로)
                        choice_id: "".to_string(),
                        affection_changes: None,
                    },
                    Choice { // check
                        text: "이욜~ 공부에 집중하겠다는 모범생 모먼트 뭐야~~ 므찐데?".to_string(),
                        next_scene_id: None,  // chapter1 씬으로 이동
                        next_line_index: Some(19),  // 무시됨 (다른 씬으로 이동하므로)
                        choice_id: "".to_string(),
                        affection_changes: None,
                    },
                    Choice {
                        text: "하긴 우리가 공부 할 시간이 어딨어 좀 힘들긴 하지..".to_string(),
                        next_scene_id: None,  // chapter1 씬으로 이동
                        next_line_index: Some(20),  // 무시됨 (다른 씬으로 이동하므로)
                        choice_id: "".to_string(),
                        affection_changes: None,
                    },
                ]),
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]), // 혼자
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "뭐야? 위로? 됐어, 괜찮아 이미 포기한건데 뭘..".to_string(),
                character_emotion: Some("hansim".to_string()),//찡그리는 표정 하나 만들기
                background: Some("oksang".to_string()),
                choices: None,
                next_line_index: Some(21),
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "그건 맞지 ㅋㅋ 너처럼 휴대폰 중독에 빠져 살지는 않으니깐~".to_string(),
                character_emotion: Some("musi".to_string()),//찡그리는 표정 하나 만들기
                background: Some("oksang".to_string()),
                choices: None,
                next_line_index: Some(21),
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine { // check
                speaker: "하나".to_string(),
                text: "어어~ 그래 이게 누나야~".to_string(),
                character_emotion: Some("musi".to_string()),//찡그리는 표정 하나 만들기
                background: Some("oksang".to_string()),
                choices: None,
                next_line_index: Some(21),
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "됐어 갑자기 뭔 푸념이냐.. 동아리 활동하러 왔으면 이거나 마저 하자".to_string(),
                character_emotion: Some("hansim".to_string()),//찡그리는 표정 하나 만들기
                background: Some("oksang".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "자자 그럼 별자리 고수 하나 누님이 같이 풀어주는 미니게임 하러 가볼까?".to_string(),
                character_emotion: Some("".to_string()),//찡그리는 표정 하나 만들기
                background: Some("oksang".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine { // check
                speaker: "하나".to_string(),
                text: "그래 그래, 아우야 나만 믿어라~".to_string(),
                character_emotion: Some("def".to_string()),
                background: None,
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: Some("constellation".to_string()),
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "조금은 재밌네 뭐, 어때 박성헌 버스 탄 기분은?".to_string(),
                character_emotion: Some("def".to_string()),//찡그리는 표정 하나 만들기
                background: Some("oksang".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "끝내주지 덕분에 수월했어".to_string(),
                character_emotion: Some("".to_string()),//찡그리는 표정 하나 만들기
                background: Some("oksang".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "가끔은 쉬는것도 나쁘진 않을 것 같네 뭐..".to_string(),
                character_emotion: Some("musi".to_string()),//찡그리는 표정 하나 만들기
                background: Some("oksang".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "그걸 이제 알았어? 온김에 바람이나 쐬고 들어가자".to_string(),
                character_emotion: Some("".to_string()),//찡그리는 표정 하나 만들기
                background: Some("oksang".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "그래.. 바람이 많이 부네, 시원해.".to_string(),
                character_emotion: Some("hansim".to_string()),//찡그리는 표정 하나 만들기
                background: Some("oksang".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "..되게 예쁘네".to_string(),
                character_emotion: Some("".to_string()),//찡그리는 표정 하나 만들기
                background: Some("oksang".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "".to_string(),
                text: "".to_string(),
                character_emotion: None,
                background: None,
                choices: None,
                next_line_index: None,
                displayed_character: None,
                visible_characters: None,
                event_image: Some("hana1".to_string()),
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "뭐..뭐라고?".to_string(),
                character_emotion: Some("buggu".to_string()),//찡그리는 표정 하나 만들기
                background: Some("oksang".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "어? 어 아니 석양이 예쁘다고...".to_string(),
                character_emotion: Some("".to_string()),//찡그리는 표정 하나 만들기
                background: Some("oksang".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "아 어어.. 어 맞지 예쁘긴 하다.".to_string(),
                character_emotion: Some("buggu".to_string()),
                background: Some("oksang".to_string()), 
                choices: Some(vec![  // 선택지 추가
                    Choice {
                        text: "뭐야? 설렜어?".to_string(),
                        next_scene_id: None,  // 같은 씬 내에서 진행
                        next_line_index: Some(33),  // 다음 라인으로 자동 진행
                        choice_id: "".to_string(),
                        affection_changes: None,
                    },
                    Choice { 
                        text: "ㅋㅋㅋㅋㅋㅋㅋㅋ 착각한건 아니지?".to_string(),
                        next_scene_id: None,  // chapter1 씬으로 이동
                        next_line_index: Some(34),  // 무시됨 (다른 씬으로 이동하므로)
                        choice_id: "".to_string(),
                        affection_changes: None,
                    },
                    Choice {
                        text: "너도 예뻐".to_string(),
                        next_scene_id: None,  // chapter1 씬으로 이동
                        next_line_index: Some(35),  // 무시됨 (다른 씬으로 이동하므로)
                        choice_id: "".to_string(),
                        affection_changes: None,
                    },
                    Choice { // check
                        text: "당황했어? 나의 큐티빠띠 작은 아기 고양이?".to_string(),
                        next_scene_id: None,  // chapter1 씬으로 이동
                        next_line_index: Some(36),  // 무시됨 (다른 씬으로 이동하므로)
                        choice_id: "".to_string(),
                        affection_changes: None,
                    },
                ]),
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]), // 혼자
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "아 진짜 이상한 소리 좀 하지마, 그럴리가 있겠냐?".to_string(),
                character_emotion: Some("buggu".to_string()),//찡그리는 표정 하나 만들기
                background: Some("oksang".to_string()),
                choices: None,
                next_line_index: Some(37),
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "착각은 무슨?? 잘 안들려서 물어본거야..!!".to_string(),
                character_emotion: Some("buggu".to_string()),//찡그리는 표정 하나 만들기
                background: Some("oksang".to_string()),
                choices: None,
                next_line_index: Some(37),
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "너가 결국 미친거야..?".to_string(),
                character_emotion: Some("hansim".to_string()),//찡그리는 표정 하나 만들기
                background: Some("oksang".to_string()),
                choices: None,
                next_line_index: Some(37),
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine { // check
                speaker: "하나".to_string(),
                text: "진짜 박성헌 죽인다 너 내가".to_string(),
                character_emotion: Some("hwana".to_string()),//찡그리는 표정 하나 만들기
                background: Some("oksang".to_string()),
                choices: None,
                next_line_index: Some(37),
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine { // check
                speaker: "성헌".to_string(),
                text: "ㅋㅋㅋㅋ 그래 그래 이제 열쇠도 얻었는데 슬슬 내려갈까?".to_string(),
                character_emotion: Some("".to_string()),//찡그리는 표정 하나 만들기
                background: Some("oksang".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "그래 좋아, 근데 이 암호는 대체 뭐지.. 진짜 감이 안잡히네".to_string(),
                character_emotion: Some("hwana".to_string()),//찡그리는 표정 하나 만들기
                background: Some("oksang".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "뭐 일단 나머지 열쇠 얻는게 먼저 아닐까?".to_string(),
                character_emotion: Some("".to_string()),//찡그리는 표정 하나 만들기
                background: Some("oksang".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "그건 맞지, 넌 이제 다음엔 어디로 가?".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("oksang".to_string()), 
                choices: Some(vec![  // 선택지 추가
                    Choice {
                        text: "음악실".to_string(),
                        next_scene_id: Some("chapter1".to_string()),  // 현재 씬에 머물기
                        next_line_index: None,  // 다음 라인으로 자동 진행
                        choice_id: "chapter1".to_string(),
                        affection_changes: None,
                    },
                    Choice {
                        text: "도서관".to_string(),
                        next_scene_id: Some("chapter3".to_string()),  // chapter1 씬으로 이동
                        next_line_index: None,  // 무시됨 (다른 씬으로 이동하므로)
                        choice_id: "chapter3".to_string(),
                        affection_changes: None,
                    },
                ]),
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]), // 혼자
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
        ],
    }
}