use super::{DialogueLine, DialogueScene};
use crate::dialogue::Choice;

pub fn create_chapter3() -> DialogueScene {
    DialogueScene {
        scene_id: "chapter3".to_string(),
        background: Some("library_bam".to_string()),
        lines: vec![
            DialogueLine {
                speaker: "나레이션".to_string(),
                text: "다음날 밤, 도서관".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["성헌".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "선...배? 계세요..?".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["성헌".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "응. 여기야 어서와. 좀 늦은 시간에 불러서 당황했지? 아무래도 저녁에 와야 편하게 대화하면서 찾을 수 있을 것 같아서".to_string(),
                character_emotion: Some("jinji".to_string()),//찡그리는 표정 하나 만들기
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "아 그러네요, 역시 선배는 생각이 깊으시네요..".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "후배가 같이 와준다는데, 선배로써 철저히 준비해야하지 않겠어?".to_string(),
                character_emotion: Some("happy".to_string()),//찡그리는 표정 하나 만들기
                background: Some("library_bam".to_string()),
                choices: Some(vec![  // 선택지 추가
                    Choice {
                        text: "아 이럴 줄 알았으면 저도 뭐라도 할걸 그랬네요..".to_string(),
                        next_scene_id: None,  // 같은 씬 내에서 진행
                        next_line_index: Some(5),  // 다음 라인으로 자동 진행
                        choice_id: "".to_string(),
                        affection_changes: None,
                    },
                    Choice {
                        text: "저는 실수하는 선배도 보고싶은데요? 너무 신경쓰지 않으셔도 괜찮아요!".to_string(),
                        next_scene_id: None,  // chapter1 씬으로 이동
                        next_line_index: Some(6),  // 무시됨 (다른 씬으로 이동하므로)
                        choice_id: "".to_string(),
                        affection_changes: None,
                    },
                    Choice {
                        text: "좋아 그럼 오늘 하루 선배만 믿겠습니다!".to_string(),
                        next_scene_id: None,  // chapter1 씬으로 이동
                        next_line_index: Some(7),  // 무시됨 (다른 씬으로 이동하므로)
                        choice_id: "".to_string(),
                        affection_changes: None,
                    },
                    Choice {
                        text: "선배의 그런 철저함이 전 너무 좋아요.".to_string(),
                        next_scene_id: None,  // chapter1 씬으로 이동
                        next_line_index: Some(8),  // 무시됨 (다른 씬으로 이동하므로)
                        choice_id: "".to_string(),
                        affection_changes: None,
                    },
                ]),
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "괜찮아 성헌이는 도서관 같이 와준걸로 충분한걸?".to_string(),
                character_emotion: Some("happy".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: Some(9),
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "그런 말 들으니까 조금 더 신경써야겠는걸? 절대 실수하는 모습을 보여줄 순 없지!".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: Some(9),
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "좋아 후배는 나만 따라오도록!".to_string(),
                character_emotion: Some("happy".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: Some(9),
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "영광인데? 우리 동아리 에이스한테 점수따면 좋지 ㅎㅎ".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: Some(9),
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "좋네요! 그럼 이제 한번 도서관을 돌아다녀볼까요?".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "사실 성헌이 너 오기 전에 좀 둘러봤는데, 의심가는 곳이 한군데 있어. 같이 가볼래?".to_string(),
                character_emotion: Some("jinji".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "네 그럼 거기부터 가시죠! 어딘가요?".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "어디냐면, 안내 데스크쪽이야.".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "안내 데스크요? 그런곳에 정말 열쇠가 숨겨져있을까요?".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "아직 확인하진 않아서 확신은 못하는데, 동아리 기록을 쭉 읽어보니까 대대로 선배님들이 사서 선생님과 친하시더라고?".to_string(),
                character_emotion: Some("gomin".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "나도 마찬가지고, 그래도 선생님을 살짝 떠봤는데 재밌어 하시면서 힌트를 주셨어.".to_string(),
                character_emotion: Some("happy".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "와.. 혜진 선배 졸업하시면 저희끼리 동아리 해야할텐데 막막하네요. 선배 없이 어떡하죠?".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "나 없이도 잘 해야지! 성헌이 넌 내가 봤을땐 충분히 잘할 것 같은데?".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine { // check
                speaker: "성헌".to_string(),
                text: "하.. 계실때 최대한 많이 배우겠습니다 ㅋㅋ".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "좋아, 자 그럼 이제 데스크쪽으로 가보자".to_string(),
                character_emotion: Some("jinji".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "흠 아직까진 크게 잘 모르겠네요.. 그냥 평소랑 다를게 없는 안내 데스큰데요..".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("library_bam2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "어 잠시만 여기 이거 봐바. 다른 책들이랑 좀 다른 것 같지 않아? 표지도 그렇고.. 유난히 두꺼운데?".to_string(),
                character_emotion: Some("gomin".to_string()),
                background: Some("library_bam2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "그러게요. 읏차.. 어라? 이거 생각보다 되게 무거운데요? 어? 선배..! 이거 책이 아닌것 같아요.".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("library_bam2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "그러게? 책 안에 공간을 파서 태블릿을 넣어뒀네, 켜볼까? 아무래도 이게 우리가 찾던 것 같은데?".to_string(),
                character_emotion: Some("jinji".to_string()),
                background: Some("library_bam2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "여기 가장 첫 장에 \'주어진 문제를 풀어라\'라고 적혀있네요. 도서관답게 지식 문제가 나오나본데요?".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("library_bam2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "너랑 나니까 수월하게 풀 수 있을거야. 한번 해보자.".to_string(),
                character_emotion: Some("happy".to_string()),
                background: Some("library_bam2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: Some("quiz".to_string()),
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "후! 마지막 문제가 유난히 어려웠네요.. 하마터면 틀릴 뻔 했어요.".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("library_bam2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "아 선배 열쇠는 여기 있어요. 선배가 마지막 문제 푸시는 동안에 둘러봤는데 좀 먼지 쌓인 상자가 있더라고요. 문제 풀자마자 열렸어요!".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("library_bam2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "성공했네. 성헌이 너랑 오길 잘했네 덕분에 수월했어, 근데 문제 풀다가 보니까 소나기가 좀 오는 것 같은데 잠깐 기다렸다가 갈까?".to_string(),
                character_emotion: Some("happy".to_string()),
                background: Some("library_bam2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            //빗소리 효과
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "어 그러게요. 비 예보 가능성 낮아서 우산을 안가져왔는데..".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("library_bam2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "괜찮아. 어차피 누가 있는것도 아니고, 잠깐 앉아서 대화하다 가자".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("library_bam2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "좋아요!".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("library_bam2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "그나저나 선배가 이런 전설을 믿으실 줄 몰랐어요.".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "왜? 나도 어릴때부터 항상 이런 모험 이야기를 동경했는걸.".to_string(),
                character_emotion: Some("ariyon".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "이런 허무맹랑한 이야기도 너무너무 좋아하고! ㅎㅎ 좀 유치한가.?".to_string(),
                character_emotion: Some("happy".to_string()),
                background: Some("library_bam".to_string()),
                choices: Some(vec![  
                    Choice {
                        text: "아니에요 낭만있잖아요. 이런 이야기 저도 참 좋아해요.".to_string(),
                        next_scene_id: None,  // 같은 씬 내에서 진행
                        next_line_index: Some(35),  // 다음 라인으로 자동 진행
                        choice_id: "".to_string(),
                        affection_changes: None,
                    },
                    Choice {
                        text: "전설이든 뭐든, 선배가 믿는다면 의미 있죠.".to_string(),
                        next_scene_id: None,  // chapter1 씬으로 이동
                        next_line_index: Some(36),  // 무시됨 (다른 씬으로 이동하므로)
                        choice_id: "".to_string(),
                        affection_changes: None,
                    },
                    Choice {
                        text: "아뇨 유치하긴요, 그냥 평소엔 티를 안내셔서 몰랐어요.".to_string(),
                        next_scene_id: None,  // chapter1 씬으로 이동
                        next_line_index: Some(37),  // 무시됨 (다른 씬으로 이동하므로)
                        choice_id: "".to_string(),
                        affection_changes: None,
                    },
                    Choice { // check
                        text: "오.. 젊게 사시네요.".to_string(),
                        next_scene_id: None,  // chapter1 씬으로 이동
                        next_line_index: Some(38),  // 무시됨 (다른 씬으로 이동하므로)
                        choice_id: "".to_string(),
                        affection_changes: None,
                    },
                ]),
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "역시 성헌이는 나랑 통하는 면이 있네?".to_string(),
                character_emotion: Some("jinji".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: Some(39),
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "맞지 지금처럼 그저 허구의 이야기가 아니고 진짜 모험이 기다리는 경우도 있는걸!".to_string(),
                character_emotion: Some("happy".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: Some(39),
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "이제 티를 마구마구 내야겠다. 성헌이는 이제 아니까 받아주는거지?".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: Some(39),
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine { // check
                speaker: "혜진".to_string(),
                text: "아무래도 요새 대세를 따라가려면 젊게 살아야지~".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: Some(39),
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "좋네요.. 선배랑 이런저런 대화도 할 수 있고..".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "그러게 이런 날씨에 도서관에 있으니까... 더 운치 있네".to_string(),
                character_emotion: Some("ariyon".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "맞아요. 뭔가 되게 영화 같아요.".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "영화라니. 우리가 주인공인 셈?".to_string(),
                character_emotion: Some("gomin".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "그런 셈이죠?".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "...".to_string(),
                character_emotion: Some("jinji".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "그럼... 어떤 영화일까?".to_string(),
                character_emotion: Some("gomin".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "글쎄요... 어드벤처? 미스터리?".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "로맨스는?".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "로... 로맨스요?".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: " ".to_string(),
                character_emotion: Some("happy".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: Some("Hjin1".to_string()),
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "농담이야. 농담! 표정 봐 진짜 웃겨".to_string(),
                character_emotion: Some("happy".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "아... 아니 이건 그냥 당황해서..".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "그치만... 완전히 농담은 아닐 수도 있지?".to_string(),
                character_emotion: Some("gomin".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "네? 그게... 무슨 뜻이에요?".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "자 자! 이제 비가 그쳤네. 이제 가자.".to_string(),
                character_emotion: Some("happy".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "아 잠시만요! 선배 대답은 해주셔야죠.!".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("library_bam".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            // 추가 대화 계속...
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "그래그래~ 나중에 기회가 된다면? 그래서 넌 다음에 어디로 가?".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("library_bam".to_string()), 
                choices: Some(vec![  // 선택지 추가
                    Choice {
                        text: "음악실".to_string(),
                        next_scene_id: Some("chapter1".to_string()),
                        next_line_index: None,
                        choice_id: "chapter1".to_string(),
                        affection_changes: None,
                    },
                    Choice {
                        text: "옥상".to_string(),
                        next_scene_id: Some("chapter2".to_string()),
                        next_line_index: None,
                        choice_id: "chapter2".to_string(),
                        affection_changes: None,
                    },
                    Choice {
                        text: "도서관".to_string(),
                        next_scene_id: Some("chapter3".to_string()),
                        next_line_index: None,
                        choice_id: "chapter3".to_string(),
                        affection_changes: None,
                    },
                ]),
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]), // 혼자
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
        ],
    }
}