use super::{DialogueLine, DialogueScene};
use crate::dialogue::Choice; // Import the Choice struct if it exists in the parent module

pub fn create_chapter1() -> DialogueScene {
    DialogueScene {
        scene_id: "chapter1".to_string(),
        background: Some("music_class".to_string()),
        lines: vec![
            
            DialogueLine {
                speaker: "나레이션".to_string(),
                text: "다음 날 오후 1시, 음악실".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["성헌".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "성헌 오빠! 왔어요?".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "어, 뭐야 은하 먼저 와 있었어?".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "앗 네! 전 입시 때문에 음악실에 거의 항상 있거든요..! ㅎㅎ".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "뭐야, 그럼 음악실은 은하만 믿으면 되겠네!".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "앗 그건 안 되는데.. 제가 아무리 자주 와도 딱히 이상한 건 못 느꼈단 말이에요!".to_string(),
                character_emotion: Some("happy".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine { 
                speaker: "성헌".to_string(), 
                text: "그래? 그럼 어쩔 수 없이 일단 더 찾아봐야겠네.".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "근데 그럼 은하는 음악실에서 뭐 연습해?".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "저는 피아노 쪽으로 가려고 생각 중이라서 와서 피아노 연습하고 있어요!".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "오, 뭐야 은하 피아노 잘치는구나?".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "앗 그건 아니에요!!".to_string(),
                character_emotion: Some("musubbutsinna".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "그냥... 조금 하는 정도? ㅎㅎ".to_string(),
                character_emotion: Some("buggu".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "그렇게 말하니까 나 너무 궁금한데, 오늘 연주 한 번 들려주는 거야?".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "어..그렇지만 오빠 앞에서 치기엔 저 조금 부끄러운데.. 막 잘하는 것도 아니고..".to_string(),
                character_emotion: Some("buggu".to_string()),
                background: Some("music_class".to_string()), 
                choices: Some(vec![  // 선택지 추가
                    Choice {
                        text: "그냥 혼자 연습한다고 생각하고 한 번만 해줘!".to_string(),
                        next_scene_id: None,  // 같은 씬 내에서 진행
                        next_line_index: Some(14),  // 다음 라인으로 자동 진행
                        choice_id: "".to_string(),
                        affection_changes: None,
                    },
                    Choice {
                        text: "에이 잘할 거 같은데?".to_string(),
                        next_scene_id: None,  // chapter1 씬으로 이동
                        next_line_index: Some(15),  // 무시됨 (다른 씬으로 이동하므로)
                        choice_id: "".to_string(),
                        affection_changes: None,
                    },
                    Choice {
                        text: "나 지금 되게 기대되는데.. 안 해 줄 거야?".to_string(),
                        next_scene_id: None,  // chapter1 씬으로 이동
                        next_line_index: Some(16),  // 무시됨 (다른 씬으로 이동하므로)
                        choice_id: "".to_string(),
                        affection_changes: None,
                    },
                    Choice { 
                        text: "아...그래? 힘들면 안해도 괜찮고...아쉬워라..".to_string(),
                        next_scene_id: None,  // chapter1 씬으로 이동
                        next_line_index: Some(17),  // 무시됨 (다른 씬으로 이동하므로)
                        choice_id: "".to_string(),
                        affection_changes: None,
                    },
                ]),
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string()]), // 혼자
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "으.. 그럼 열쇠 찾으면 한번 생각해볼게요..".to_string(),
                character_emotion: Some("buggu".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: Some(18),
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "그럼 저 마음의 준비를 할 시간은 주세요..!".to_string(),
                character_emotion: Some("buggu".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: Some(18),
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "으아, 해 드리려구 했는데 그렇게 말하니까 더 긴장되잖아요!!".to_string(),
                character_emotion: Some("musubbutsinna".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: Some(18),
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "아니.. 그런게 아닌데.. 열쇠만 찾고 해드릴게요..".to_string(),
                character_emotion: Some("pigim".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: Some(18),
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "ㅋㅋㅋ 알았어 미안미안, 그나저나 피아노에 이 버튼은 원래 있었던 거야?".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "어? 이게 뭐지..? 저 완전 처음 보는 버튼이에요! 평소에 키보드보다는 클래식 피아노를 자주 쳐서..".to_string(),
                character_emotion: Some("banjjack".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "엇, 여기 종이가 껴 있는데?".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "\'들려주는 음을 듣고 따라 치세요?\' 아무래도 이건 은하 너가 나보다 더 잘할 것 같네.".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "아니에요, 오빠! 한 번 같이 해봐요! 제가 도와드릴게요!".to_string(),
                character_emotion: Some("happy".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "그래, 한 번 같이 해보자 그러면.".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                sound_effect: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: Some("piano_tiles".to_string()),
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "역시 은하.. 확실히 전문가랑 하니까 수월하게 했네, 고마워".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "저야말로 도와주러 오신 거니까 너무 감사하죠!".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "아, 맞아. 은하야, 이제 연주 해 주는 건가?".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "아.. 아 맞다.. 진짜 부끄러운데... 오빠 부탁이니까 특별히 오늘만 한 번 보여 드리는 거예요?".to_string(),
                character_emotion: Some("buggu".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "".to_string(),
                text: "".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: None,
                visible_characters: None,
                event_image: Some("unha1".to_string()), 
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "우와 은하 진짜 대단하다.. 역시 피아노 전공은 뭔가 다르네.".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["성헌".to_string(),"은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "저 진짜 실수 많이 했는데.. 괜찮았어요?".to_string(),
                character_emotion: Some("musubbutsinna".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["성헌".to_string(),"은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "음? 난 전혀 몰랐어, 실수를 했어?".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["성헌".to_string(),"은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "ㅎㅎ 못 들으셨으면 다행이네요! 오빠 앞에서 연주하는 건 처음이라 조금 실수했어요..".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["성헌".to_string(),"은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "그나저나 이번에도 열쇠에 이상한 문구가 적혀 있네요? 역시 암호려나요?".to_string(),
                character_emotion: Some("banjjack".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["성헌".to_string(),"은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "ㅋㅋㅋㅋ 은하가 모험을 진짜 좋아하는구나? 아무래도 암호이지 않을까? 아니면 굳이 이런 문구가 들어갈 일이 없으니까".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["성헌".to_string(),"은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(), 
                text: "아직은 뭔지 전혀 감이 안 잡히네요..".to_string(),
                character_emotion: Some("musubbutsinna".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["성헌".to_string(),"은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "굳이 지금 감 잡을 필요가 있을까? 아직 얻지 못한 열쇠도 많으니까 성급하지 않아도 될 것 같아.".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["성헌".to_string(),"은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "그쵸? 그렇겠죠?".to_string(),
                character_emotion: Some("banjjack".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["성헌".to_string(),"은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "오늘 진짜 감사해요! 혼자였으면 키보드에 버튼이 있는 걸 뒤늦게 알았을 것 같아요 ㅎㅎ".to_string(),
                character_emotion: Some("happy".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["성헌".to_string(),"은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "나야말로 오늘 은하랑 같이 할 수 있어서 재밌었어, 나보다 하나 아니면 혜진 선배랑 같이 하는 게 더 편했을 텐데.. 괜히 미안하네..".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("music_class".to_string()),
                choices: None,  
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["성헌".to_string(),"은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "네? 아니에요!! 저는.. 저는 오히려 오빠랑 더 가까워진 것 같아서 좋았어요!!".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["성헌".to_string(),"은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "아, 아니아니 그러니까 그런 말이 아니고요..!! 그냥 친해져서 좋다는 말이었어요!!".to_string(),
                character_emotion: Some("buggu".to_string()),
                background: Some("music_class".to_string()),
                choices: Some(vec![
                    Choice {
                        text: "뭐야 ㅋㅋ 아~ 은하가 나랑 친해지고 싶었구나?".to_string(),
                        next_scene_id: None,
                        next_line_index: Some(42),
                        choice_id: "".to_string(),
                        affection_changes: None,
                    },
                    Choice { 
                        text: "은하가 이런 말도 할 줄 알고.. 다 컸네!".to_string(),
                        next_scene_id: None,
                        next_line_index: Some(43),
                        choice_id: "".to_string(),
                        affection_changes: None,
                    },
                    Choice {
                        text: "뭘 정정까지 해 ㅋㅋ 나도 은하랑 가까워져서 좋아".to_string(),
                        next_scene_id: None,
                        next_line_index: Some(44),
                        choice_id: "".to_string(),
                        affection_changes: None,
                    },
                    Choice {
                        text: "ㅋㅋㅋㅋ 그게 뭐야 역시 은하는 참 솔직해서 좋다니까".to_string(),
                        next_scene_id: None,
                        next_line_index: Some(45),
                        choice_id: "".to_string(),
                        affection_changes: None,
                    },
                ]),
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["성헌".to_string(),"은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "으아아 아니 저는 하나 언니랑 혜진 언니처럼 많이 친해지지 못한거같아서...".to_string(),
                character_emotion: Some("buggu".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: Some(46),
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["성헌".to_string(),"은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "아 놀리지 마세요..! 오늘따라 말이 이상하게 나와서 그래요!!!".to_string(),
                character_emotion: Some("musubbutsinna".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: Some(46),
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["성헌".to_string(),"은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "아 몰라요 오빠 못 들은 걸로 해주세요.!".to_string(),
                character_emotion: Some("buggu".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: Some(46),
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["성헌".to_string(),"은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "솔직한 게 아니고 실수한 거에요.. ㅠㅠ 저도 제가 왜 그랬는지 모르겠어요..".to_string(),
                character_emotion: Some("musubbutsinna".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: Some(46),
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["성헌".to_string(),"은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "괜찮아 ㅋㅋ 앞으로 더 친해지면 되잖아? 많이 친해져서 다같이 축제도 놀러가자".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["성헌".to_string(),"은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "네..! 좋아요! 사실은.. 늘 음악실로 와서 연습하다보니 저 친구가 없거든요..".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["성헌".to_string(),"은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "ㅎㅎ 그래도 타임캡슐 덕분에 언니 오빠들이랑 친해질 수 있어서 너무 기뻤어요, 저!".to_string(),
                character_emotion: Some("buggu".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["성헌".to_string(),"은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "그래? 은하가 워낙 늘 밝아서 그런 고민이 있는 줄은 몰랐네, 걱정마! 앞으로 시간은 많아.".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["성헌".to_string(),"은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "그쵸! 아직 모험도 안 끝났구요!".to_string(),
                character_emotion: Some("banjjack".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["성헌".to_string(),"은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            // [수업 종치는 소리]
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "앗 이제 수업 시작하나보다. 이제 슬슬 돌아가자!".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("music_class".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["성헌".to_string(),"은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "네! 오빠는 이제 어디로 가세요?".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("music_class".to_string()),
                choices: Some(vec![  // 선택지 추가
                    Choice {
                        text: "옥상".to_string(),
                        next_scene_id: Some("chapter2".to_string()),  // 현재 씬에 머물기
                        next_line_index: None,  // 다음 라인으로 자동 진행
                        choice_id: "chapter2".to_string(),
                        affection_changes: None,
                    },
                    Choice {
                        text: "도서관".to_string(),
                        next_scene_id: Some("chapter3".to_string()),  // chapter1 씬으로 이동
                        next_line_index: None,  // 무시됨 (다른 씬으로 이동하므로)
                        choice_id: "chapter3".to_string(),
                        affection_changes: None,
                    },
                ]),
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["성헌".to_string(),"은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
        ],
    }
}