use super::{DialogueLine, DialogueScene};

pub fn create_end_1() -> DialogueScene {
    DialogueScene {
        scene_id: "end_1".to_string(),
        background: Some("secert_room".to_string()),
        lines: vec![
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "어..? 이거.. 암호 풀린건가?".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some(" ".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "오? 풀렸네? 우리가 맞았나봐.".to_string(),
                character_emotion: Some("gomin".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "와 대박.... 결국 이게 진짜였네..".to_string(),
                character_emotion: Some("hansim".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "헐! 대박! 어서 읽어봐요!!".to_string(),
                character_emotion: Some("banjjack".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "\'뒤쪽 사물함 왼쪽에서 4번째, 아래쪽 칸\'이라고 적혀있는데?".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some(" ".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "왼쪽에서 네번째..아래.... 앗 여깄다!".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "여기 상자가 있는데?".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "드디어 타임캡슐을 찾았네? 정말 말도 안되는 일이라고 생각했는데..".to_string(),
                character_emotion: Some("happy".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "자 그럼 다 모였지..? 연다..?".to_string(),
                character_emotion: Some("hwana".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "이건..".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some(" ".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "쪽지 하나랑.. 이건..... 예쁜 돌맹이..?".to_string(),
                character_emotion: Some("banjjack".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "\'소문에 이끌려 결국 이 곳까지 도달한 당신들에게 경의를 표합니다. 여기까지 온 당신들이라면 당신들이 원하던 소원은 반드시 이뤄질 것 입니다.\'".to_string(),
                character_emotion: Some("jinji".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "\'이 돌멩이는 당신들의 용기의 증표입니다.\'..?".to_string(),
                character_emotion: Some("hwana".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "뭐야 결국 이럴 줄 알았어. 하긴 소원을 이뤄주는 게 가당키나 하냐?".to_string(),
                character_emotion: Some("hansim".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "음.. 근데 전 이 말 맞는 것 같아요..!".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "제 소원은 이뤄진 것 같거든요..!".to_string(),
                character_emotion: Some("buggu".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "나도 얼추? 성공적인 모험인 것 같은데?".to_string(),
                character_emotion: Some("happy".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "허 참.. 소원이 다들 그렇게 소박해서 어떡해? 야 너가 말해봐, 소원 이뤄졌어?".to_string(),
                character_emotion: Some("buggu".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "아니~ 근데 내 소원은 다들 협조 좀만 해주면 이룰 수 있을 것 같긴 해.".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some(" ".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "음? 협조?".to_string(),
                character_emotion: Some("gomin".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "네, 이제 체육관에서 하셨던 약속을 지키셔야죠?".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some(" ".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "아! 설마! 회비로 회식하는거요?!".to_string(),
                character_emotion: Some("banjjack".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "하하 그러네 그게 있었구나?".to_string(),
                character_emotion: Some("happy".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "우와! 좋아요! 맛있는거 먹으러 가요!".to_string(),
                character_emotion: Some("banjjack".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "최근에 들었던 얘기중에 가장 맘에 들었어.".to_string(),
                character_emotion: Some("musi".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "자자, 그럼 이제 이 먼지나고 더러운 교실을 제발 탈출하자고!".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "".to_string(),
                text: "".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some(" ".to_string()),
                visible_characters: None, 
                event_image: Some("ending_image".to_string()),
                minigame_trigger: None,
                sound_effect: None,
            },
        ],
    }
}