use super::{DialogueLine, DialogueScene};

pub fn create_end_0() -> DialogueScene {
    DialogueScene {
        scene_id: "end_0".to_string(),
        background: Some("gu_bokdo".to_string()),
        lines: vec![
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "말도안돼 드디어 모든 열쇠를 다 모았다..!".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("gu_bokdo".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some("".to_string()),
                visible_characters: Some(vec!["".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "그니깐요!! 진짜 너무 신나요!".to_string(),
                character_emotion: Some("happy".to_string()),
                background: Some("gu_bokdo".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "그러게, 여기까지 오니까 좀 궁금하네 이 뒤에 뭐가 있을지..".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("gu_bokdo".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "지금까지 수고 많았어, 이제 한번 하나의 궁금증을 해결하러 가볼까?".to_string(),
                character_emotion: Some("happy".to_string()),
                background: Some("gu_bokdo".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            //문 열리는 소리
            DialogueLine {
                speaker: "하나".to_string(),
                text: "콜록 콜록 뭐, 뭐야? 그냥 안쓰는 창고 느낌의 교실 같은데? 먼지도 엄청 쌓였네.".to_string(),
                character_emotion: Some("musub".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "으 그러게요.. 청소 안한지 엄청 오래됐나봐요....".to_string(),
                character_emotion: Some("musub".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "여기에 그 문서가 있을 것 같진 않은데? 여기서 뭘 또 해야하는걸까..?".to_string(),
                character_emotion: Some("gomin".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "그나마 저 컴퓨터가 좀 의심스럽지 않아요.? 저쪽으로 가보는건 어때요?".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some(" ".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "헉 그러네요, 먼지가 너무 심해서 컴퓨터 존재를 잊었네요.!".to_string(),
                character_emotion: Some("happy".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "나도 마침 같은 생각이였어, 저쪽으로 한번 가보자.".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "하 진짜 먼지 이거 좀 아닌거같은데.. 없으면 바로 나가는거다.".to_string(),
                character_emotion: Some("hwana".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "어 컴퓨터 키니까 텍스트 파일 하나랑 압축파일 하나가 있네요?".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some(" ".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "\'지금까지 모은 열쇠의 문자들을 올바른 암호로 바꿔서 압축파일을 푸세요.\'라네요?".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some(" ".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "아! 지금까지 열쇠에 적힌 그 암호들이 여기에 쓰이나봐요!".to_string(),
                character_emotion: Some("banjjack".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "뭐야, 그런거였어? 열쇠만 얻었다고 되는게 아니였네..".to_string(),
                character_emotion: Some("hansim".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "일단 그래도 지금까지 열쇠에 적혀있던 내용은 아니까, 한번 풀어보자.".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: " ".to_string(),
                text: " ".to_string(),
                character_emotion: Some(" ".to_string()),
                background: Some("secret_room".to_string()), 
                choices: None,
                next_line_index: None,
                displayed_character: Some(" ".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: Some("pwd".to_string()),
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "이제 한번 입력해볼까?".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("secret_room".to_string()),
                choices: None,
                next_line_index: None,
                sound_effect: None,
                displayed_character: Some(" ".to_string()),
                visible_characters: Some(vec!["은하".to_string(), "하나".to_string(), "혜진".to_string()]), 
                event_image: None,
                minigame_trigger: Some("check_key".to_string()),
            },
        ],
    }
}