use super::{DialogueLine, DialogueScene};
use crate::dialogue::Choice;

pub fn create_intro_scene() -> DialogueScene {
    DialogueScene {
        scene_id: "intro".to_string(),
        background: Some("classroom".to_string()),
        lines: vec![
            DialogueLine {
                speaker: "나레이션".to_string(),
                text: "2025년 0X월 XX일, 교실".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("classroom".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["성헌".to_string()]), // 혼자
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
                DialogueLine {
                    speaker: "성헌".to_string(),
                    text: "또 비가 오네.. 오늘 체육시간도 실내로 바뀌겠다.".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("classroom".to_string()),
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("성헌".to_string()),
                    visible_characters: Some(vec!["성헌".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "하나".to_string(),
                    text: "야 박성헌 너 그 얘기 들었어?".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("classroom".to_string()),
                    next_line_index: None,
                    choices: None,
                    displayed_character: Some("하나".to_string()),
                    visible_characters: Some(vec!["성헌".to_string(), "하나".to_string()]), // 둘이
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "성헌".to_string(),
                    text: "응? 갑자기? 무슨 소문?".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("classroom".to_string()), 
                    next_line_index: None,
                    choices: None,
                    displayed_character: Some("성헌".to_string()),
                    visible_characters: Some(vec!["성헌".to_string(), "하나".to_string()]), // 둘이
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "하나".to_string(),
                    text: "소원을 이뤄준다는 타임캡슐 말이야. 완전 헛소리 같지 않아?".to_string(),
                    character_emotion: Some("musi".to_string()),
                    background: Some("classroom".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("하나".to_string()),
                    visible_characters: Some(vec!["성헌".to_string(), "하나".to_string()]), // 둘이
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "성헌".to_string(),
                    text: "타임캡슐? 그게 뭔데?".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("classroom".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("성헌".to_string()),
                    visible_characters: Some(vec!["성헌".to_string(), "하나".to_string()]), 
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "하나".to_string(),
                    text: "몰라 글쎄 학교 어딘가에 숨겨져 있다는데? 찾으면 졸업 전에 뭐든 소원을 이룰 수 있다나 뭐라나.".to_string(),
                    character_emotion: Some("musi".to_string()),
                    background: Some("classroom".to_string()),
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("하나".to_string()),
                    visible_characters: Some(vec!["성헌".to_string(), "하나".to_string()]), // 셋이
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "하나".to_string(),
                    text: "암튼 3학년들이 그거땜에 지금 난리야".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("classroom".to_string()),
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("하나".to_string()),
                    visible_characters: Some(vec!["성헌".to_string(), "하나".to_string()]), // 셋이
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "성헌".to_string(),
                    text: "에이, 그런 게 어디 있어. 그냥 스트레스 받는 3학년이 만들어낸 헛소리겠지.. 자주 있잖아 복도에서 괴성을 지르는 3학년들..".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("classroom".to_string()),
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("성헌".to_string()),
                    visible_characters: Some(vec!["성헌".to_string(), "하나".to_string()]), // 셋이
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "하나".to_string(),
                    text: "아무래도 그렇지? 근데 의외로 믿는 애들 많더라, 심지어 우리 반 의태도 어제 몰래 학교에 남아서 뭔가 찾아다녔던데?".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("classroom".to_string()),
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("하나".to_string()),
                    visible_characters: Some(vec!["성헌".to_string(), "하나".to_string()]), // 셋이
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "성헌".to_string(),
                    text: "걔가? 절대 그런거 안 믿을 것 같은데..".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("classroom".to_string()),
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("하나".to_string()),
                    visible_characters: Some(vec!["성헌".to_string(), "하나".to_string()]), // 셋이
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "하나".to_string(),
                    text: "그러게, 근데 난 안 믿기긴 해 말이 되는 소리여야지..".to_string(),
                    character_emotion: Some("musi".to_string()),
                    background: Some("classroom".to_string()),
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("하나".to_string()),
                    visible_characters: Some(vec!["성헌".to_string(), "하나".to_string()]), // 셋이
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "나레이션".to_string(),
                    text: "잠시후, 복도".to_string(), // 복도 이미지 차후 약간 수정할 것
                    character_emotion: Some("def".to_string()),
                    background: Some("bokdo".to_string()),
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("성헌".to_string()),
                    visible_characters: Some(vec!["성헌".to_string()]),
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "은하".to_string(),
                    text: "오빠! 오빠도 들었어요? 그 전설의 타임캡슐!!".to_string(),
                    character_emotion: Some("banjjack".to_string()),
                    background: Some("bokdo".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("은하".to_string()),
                    visible_characters: Some(vec!["은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "성헌".to_string(),
                    text: "어? 은하야 너도 알고있어?".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("bokdo".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("성헌".to_string()),
                    visible_characters: Some(vec!["은하".to_string()]), 
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "은하".to_string(),
                    text: "네!! 진짜 신기하지 않아요? 우리 학교에 그런 재밌는 전설이 있었다니..! 혹시 진짜일까요?".to_string(),
                    character_emotion: Some("def".to_string()), //은하 표정 추후 수정
                    background: Some("bokdo".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("은하".to_string()),
                    visible_characters: Some(vec!["은하".to_string()]), 
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "하나".to_string(),
                    text: "너무 순진한 거 아니야? 그런게 진짜 있었으면 진작 누가 가져갔겠지~".to_string(),
                    character_emotion: Some("musi".to_string()), //하나 표정 추후 수정
                    background: Some("bokdo".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("하나".to_string()),
                    visible_characters: Some(vec!["은하".to_string(), "하나".to_string()]), 
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "은하".to_string(),
                    text: "언니는 너무 현실적이에요! 꿈이 있어야죠!".to_string(),
                    character_emotion: Some("pigim".to_string()), //은하 표정 추후 수정 삐진 표정
                    background: Some("bokdo".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("은하".to_string()),
                    visible_characters: Some(vec!["은하".to_string(), "하나".to_string()]), 
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "하나".to_string(),
                    text: "꿈이야 좋지만, 현실을 봐야지. 너무 말이 안되는 소문이잖아, 구체적인 근거도 없고".to_string(),
                    character_emotion: Some("hansim".to_string()),
                    background: Some("bokdo".to_string()),
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("하나".to_string()),
                    visible_characters: Some(vec!["은하".to_string(), "하나".to_string()]), // 셋이
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "은하".to_string(),
                    text: "아! 혜진언니라면 뭔가 알고있지 않을까요?".to_string(),
                    character_emotion: Some("banjjack".to_string()),
                    background: Some("bokdo".to_string()),
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("은하".to_string()),
                    visible_characters: Some(vec!["은하".to_string(), "하나".to_string()]), // 셋이
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "성헌".to_string(),
                    text: "오? 그럴지도 몰라. 마침 심심한데 선배한테 찾아가보자.".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("bokdo".to_string()),
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("성헌".to_string()),
                    visible_characters: Some(vec!["은하".to_string(), "하나".to_string()]), // 셋이
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {

                    speaker: "나레이션".to_string(),
                    text: "잠시후, 도서관 앞".to_string(), // 복도 이미지 차후 약간 수정할 것
                    character_emotion: Some("def".to_string()),
                    background: Some("library".to_string()),
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("성헌".to_string()),
                    visible_characters: Some(vec!["성헌".to_string()]),
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "혜진".to_string(),
                    text: "음? 무슨일이야? 복도가 시끄럽네".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("library".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("혜진".to_string()),
                    visible_characters: Some(vec!["혜진".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "성헌".to_string(),
                    text: "아 지금 타임캡슐 전설이 교내에 쫙 퍼져서 그럴거에요.".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("library".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("성헌".to_string()),
                    visible_characters: Some(vec!["혜진".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "혜진".to_string(),
                    text: "아 그거? 나도 관심 있었는데. 실제로 우리 동아리 역사를 찾아보니까 흥미로운 기록들이 있더라.".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("library".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("혜진".to_string()),
                    visible_characters: Some(vec!["혜진".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "하나".to_string(),
                    text: "하 설마 선배도 이런 소문을 믿고있다니..".to_string(),
                    character_emotion: Some("hansim".to_string()), // 이미지 수정
                    background: Some("library".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("하나".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "은하".to_string(),
                    text: "역시 혜진언니라면 알고있을 것 같았어!!".to_string(),
                    character_emotion: Some("happy".to_string()), // 눈 반짝 이미지
                    background: Some("library".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("은하".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string(), "은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "혜진".to_string(),
                    text: "때로는 전설에도 나름의 근거가 있는 법이야. 그리고.... 방금 구관에서 좀 이상한걸 찾았거든.".to_string(),
                    character_emotion: Some("gomin".to_string()), // 혜진 이미지 수정
                    background: Some("library".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("혜진".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string(), "은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "은하".to_string(),
                    text: "이상한거요?? 그게 뭐에요?".to_string(),
                    character_emotion: Some("banjjack".to_string()), // 눈 반짝 이미지
                    background: Some("library".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("은하".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string(), "은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "혜진".to_string(),
                    text: "벽에 뭔가 새겨진 것 같은데...혼자서는 확인하기 어려워서.".to_string(),
                    character_emotion: Some("jinji".to_string()),  // 이미지 수정
                    background: Some("library".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("혜진".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string(), "은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "성헌".to_string(),
                    text: "음.. 마침 시험도 끝났고 동아리 활동 겸 방과후에 같이 가볼까요?".to_string(),
                    character_emotion: Some("def".to_string()),  
                    background: Some("library".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("성헌".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string(), "은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "혜진".to_string(),
                    text: "좋아 내가 안내할게. 마침 우리 동아리랑 관련있는 것 같아서 가보려고 했거든".to_string(),
                    character_emotion: Some("def".to_string()),  
                    background: Some("library".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("혜진".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string(), "은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "은하".to_string(),
                    text: "야호!! 보물찾기다!".to_string(),
                    character_emotion: Some("happy".to_string()),  
                    background: Some("library".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("은하".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string(), "은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "하나".to_string(),
                    text: "하... 진짜 다들 미쳤나봐".to_string(),
                    character_emotion: Some("hwana".to_string()),  
                    background: Some("library".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("하나".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string(), "은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "나레이션".to_string(),
                    text: "그렇게 동아리 선배들이 남겼다고 추정되는 타임캡슐을 찾기 위한 우리 넷의 모험이 시작됐다.".to_string(),
                    character_emotion: Some("def".to_string()),  
                    background: Some("library".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("나레이션".to_string()),
                    visible_characters: Some(vec!["나레이션".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "나레이션".to_string(),
                    text: "오후 6시, 구관 6층 복도".to_string(),
                    character_emotion: Some("def".to_string()),  
                    background: Some("gu_bokdo".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("나레이션".to_string()),
                    visible_characters: Some(vec!["나레이션".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "은하".to_string(),
                    text: "으으..여긴 진짜 너무 무서운 것 같아요. 방과후라 그런지 훨씬 으스스!".to_string(),
                    character_emotion: Some("musub".to_string()),  
                    background: Some("gu_bokdo".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("은하".to_string()),
                    visible_characters: Some(vec!["은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "혜진".to_string(),
                    text: "그러게 확실히 좀 어두워져서 그런지 분위기가 별로네".to_string(),
                    character_emotion: Some("gomin".to_string()),  //이미지 아쉬운데ㅠㅠ
                    background: Some("gu_bokdo".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("혜진".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "하나".to_string(),
                    text: "에이 이정도는 뭐 전혀 안무섭지.. 진짜... 하나도.......".to_string(),
                    character_emotion: Some("musub".to_string()),  //안색 안좋은 표정
                    background: Some("gu_bokdo".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("하나".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "은하".to_string(), "하나".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "성헌".to_string(),
                    text: "음? 여기가 맞나요, 선배?".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("gu_bokdo".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("성헌".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "은하".to_string(), "하나".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "혜진".to_string(),
                    text: "맞아. 이 부분을 봐. 여기 뭔가 벽돌 색이 미묘하게 다르지 않아?".to_string(),
                    character_emotion: Some("jinji".to_string()),
                    background: Some("gu_bokdo".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("혜진".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "은하".to_string(), "하나".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "하나".to_string(),
                    text: "그냥 오래돼서 그런 거 아니야?".to_string(),
                    character_emotion: Some("hansim".to_string()),
                    background: Some("gu_bokdo".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("하나".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "은하".to_string(), "하나".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "은하".to_string(),
                    text: "아니에요! 분명 뭔가 있을거에요!".to_string(),
                    character_emotion: Some("musubbutsinna".to_string()),
                    background: Some("gu_bokdo".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("은하".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "은하".to_string(), "하나".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                //쿠르릉 소리 나기
                DialogueLine {
                    speaker: "성헌".to_string(),
                    text: "어라? 이거 눌리는데?".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("gu_bokdo".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("성헌".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "은하".to_string(), "하나".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "".to_string(),
                    text: "".to_string(),
                    character_emotion: None,
                    background: None,
                    choices: None,
                    next_line_index: None,
                    displayed_character: None,
                    visible_characters: None,
                    event_image: Some("secret_door".to_string()),
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "혜진".to_string(),
                    text: "오각형... 다섯 개의 흠이 있어.".to_string(),
                    character_emotion: Some("jinji".to_string()),
                    background: Some("gu_bokdo".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("혜진".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "은하".to_string(), "하나".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "성헌".to_string(),
                    text: "각 흠마다 다른 문양이 새겨져 있고.. 쪽지도 있네.".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("gu_bokdo".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("성헌".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "은하".to_string(), "하나".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "하나".to_string(),
                    text: "뭐라고 쓰여 있는데?".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("gu_bokdo".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("하나".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "은하".to_string(), "하나".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "성헌".to_string(),
                    text: "\'다섯 개의 기억이 모일 때 진실의 문이 열리리, 각각의 시련을 통과하라.\'".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("gu_bokdo".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("성헌".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "은하".to_string(), "하나".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "은하".to_string(),
                    text: "다섯 개요? 그럼 우리 넷이서는 못하는 건가요?".to_string(),
                    character_emotion: Some("musubbutsinna".to_string()),
                    background: Some("gu_bokdo".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("은하".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "은하".to_string(), "하나".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "혜진".to_string(),
                    text: "으음.. 그건 아닌거같아, 여기 봐 작은 글씨가 더 적혀있어.".to_string(),
                    character_emotion: Some("gomin".to_string()),
                    background: Some("gu_bokdo".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("혜진".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "은하".to_string(), "하나".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "혜진".to_string(),
                    text: "\'여러 마음이 하나되어 시련을 이겨내리..\'".to_string(),
                    character_emotion: Some("jinji".to_string()),
                    background: Some("gu_bokdo".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("혜진".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "은하".to_string(), "하나".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "하나".to_string(),
                    text: "뭐 그럼 됐네, 같이 해도 된다는 거 아냐?".to_string(),
                    character_emotion: Some("hansim".to_string()),
                    background: Some("gu_bokdo".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("하나".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "은하".to_string(), "하나".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "성헌".to_string(),
                    text: "그런 것 같아. 각 흠 옆에 장소를 나타내는 그림들이 있어.".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("gu_bokdo".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("성헌".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "은하".to_string(), "하나".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "혜진".to_string(),
                    text: "어디보자, 도서관이랑 옥상, 음악실, 체육관.. 그리고 이건 과학실인 것 같아.".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("gu_bokdo".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("혜진".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "은하".to_string(), "하나".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "은하".to_string(),
                    text: "우와! 완전 설레요, 우리 당장 가요!".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("gu_bokdo".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("은하".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "은하".to_string(), "하나".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "하나".to_string(),
                    text: "흠.. 뭐 이렇게까지 자세히 있는 거 보니까, 근거없는 소문은 아니였네?".to_string(),
                    character_emotion: Some("musi".to_string()),
                    background: Some("gu_bokdo".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("하나".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "은하".to_string(), "하나".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "성헌".to_string(),
                    text: "그럼 우리가 이 다섯 곳을 다 가서 뭔가를 해결해야 하는 건가?".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("gu_bokdo".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("성헌".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "은하".to_string(), "하나".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "혜진".to_string(),
                    text: "맞는 것 같아, 각 장소에 특별한 과제가 있을 거야.".to_string(),
                    character_emotion: Some("happy".to_string()),
                    background: Some("gu_bokdo".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("혜진".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "은하".to_string(), "하나".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "은하".to_string(),
                    text: "그럼 지금 당장 시작해요!".to_string(),
                    character_emotion: Some("banjjack".to_string()),
                    background: Some("gu_bokdo".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("은하".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "은하".to_string(), "하나".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "하나".to_string(),
                    text: "지금? 벌써 많이 어두운데..".to_string(),
                    character_emotion: Some("musub".to_string()),
                    background: Some("gu_bokdo".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("하나".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "은하".to_string(), "하나".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "혜진".to_string(),
                    text: "시간이 좀 늦긴 하네, 그럼 가장 가까운 곳만 한번 가볼까?".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("gu_bokdo".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("혜진".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "은하".to_string(), "하나".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "성헌".to_string(),
                    text: "체육관이 제일 가깝겠네, 오늘은 일단 체육관만 가볼까요?".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("gu_bokdo".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("성헌".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "은하".to_string(), "하나".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "은하".to_string(),
                    text: "좋아요! 다같이 가요!".to_string(),
                    character_emotion: Some("happy".to_string()),
                    background: Some("gu_bokdo".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("은하".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "은하".to_string(), "하나".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "나레이션".to_string(),
                    text: "체육관, 저녁 7시".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("gym".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("나레이션".to_string()),
                    visible_characters: Some(vec!["나레이션".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "혜진".to_string(),
                    text: "저녁에도 불이 다 켜져있네.".to_string(),
                    character_emotion: Some("jinji".to_string()),
                    background: Some("gym".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("혜진".to_string()),
                    visible_characters: Some(vec!["혜진".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "하나".to_string(),
                    text: "아마 방금까지 운동부에서 연습했을거야.".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("gym".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("하나".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "은하".to_string(),
                    text: "다행이다.. 불 꺼져있었으면 좀 무서웠을 것 같아요..".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("gym".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("은하".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string(), "은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "성헌".to_string(),
                    text: "음? 저기 구석에 뭔가 이상한게 있어.".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("gym".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("성헌".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string(), "은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "혜진".to_string(),
                    text: "그러게, 이렇게 티나게 의심스러운게 있는데 왜 평소에 몰랐지?".to_string(),
                    character_emotion: Some("gomin".to_string()),
                    background: Some("gym".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("혜진".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string(), "은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "하나".to_string(),
                    text: "흠? 버튼인가? 4개가 있네".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("gym".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("하나".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string(), "은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "은하".to_string(),
                    text: "엇 여기 뭐가 젹혀있어요!".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("gym".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("은하".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string(), "은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "은하".to_string(),
                    text: "\"보여주는 버튼 순서를 기억해서 올바른 순서로 눌러주세요..?\"".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("gym".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("은하".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string(), "은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "성헌".to_string(),
                    text: "보여주는..? 어디서 보여주는 거지?".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("gym".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("성헌".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string(), "은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "하나".to_string(),
                    text: "해보면 알겠지, 우선 해보던가".to_string(),
                    character_emotion: Some("hansim".to_string()),
                    background: Some("gym".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("하나".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string(), "은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "혜진".to_string(),
                    text: "나도 같은 생각이야, 일단 정보가 쌓이지 않을까?".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("gym".to_string()),
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("혜진".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string(), "은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: Some("button_sequence".to_string()),
                    sound_effect: None,
                },
                DialogueLine {
                    speaker: "".to_string(),
                    text: "".to_string(),
                    character_emotion: None,
                    background: None,
                    choices: None,
                    next_line_index: None,
                    displayed_character: None,
                    visible_characters: None,
                    event_image: Some("win_minigame".to_string()),
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "은하".to_string(),
                    text: "우와! 우리가 해냈어요!!".to_string(),
                    character_emotion: Some("happy".to_string()),
                    background: Some("gym".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("은하".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string(), "은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "하나".to_string(),
                    text: "열쇠도 줬네, 그나저나 열쇠에 새겨진 이 문자는 뭐지..? 뭔가 암호화된 문자같은데..".to_string(),
                    character_emotion: Some("def".to_string()), //진지 표정 하나 만들기
                    background: Some("gym".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("하나".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string(), "은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "혜진".to_string(),
                    text: "우선 모든 장소를 다 가보면 알게되지 않을까 싶어".to_string(),
                    character_emotion: Some("happy".to_string()),
                    background: Some("gym".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("혜진".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string(), "은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "혜진".to_string(),
                    text: "그나저나 되게 쉽게 끝났네? 역시 우리 동아리는 단합이 잘되는구나".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("gym".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("혜진".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string(), "은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "은하".to_string(),
                    text: "그러게요! 저희 좀 잘 맞는 것 같아요!".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("gym".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("은하".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string(), "은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "하나".to_string(),
                    text: "뭐 나쁘진 않네..".to_string(),
                    character_emotion: Some("buggu".to_string()),
                    background: Some("gym".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("하나".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string(), "은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "혜진".to_string(),
                    text: "근데 확실히 하나 하는데 시간이 훌쩍 지났네".to_string(),
                    character_emotion: Some("jinji".to_string()),
                    background: Some("gym".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("혜진".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string(), "은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "성헌".to_string(),
                    text: "그러게요, 아무래도 다음 장소부터는 인원을 좀 나누는게 어떨까요?".to_string(),
                    character_emotion: Some("".to_string()),
                    background: Some("gym".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("성헌".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string(), "은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "하나".to_string(),
                    text: "좋은 생각인데? 확실히 각자 할 일도 있고.. 난 갈거면 옥상으로 가고싶어".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("gym".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("하나".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string(), "은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "은하".to_string(),
                    text: "으음 저는 음악실이요!".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("gym".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("은하".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string(), "은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "혜진".to_string(),
                    text: "그렇다면, 난 도서관으로 할게".to_string(),
                    character_emotion: Some("happy".to_string()),
                    background: Some("gym".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("혜진".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string(), "은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "혜진".to_string(),
                    text: "흠 그치만 적어도 두명씩은 가줬으면 좋겠는데.. 시간 좀 괜찮은 사람 있어?".to_string(),
                    character_emotion: Some("jinji".to_string()),
                    background: Some("gym".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("혜진".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string(), "은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "하나".to_string(),
                    text: "난 학원이 있어서 많은 시간 내긴 힘들 것 같은데?".to_string(),
                    character_emotion: Some("hansim".to_string()), //표정 수정
                    background: Some("gym".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("하나".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string(), "은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "은하".to_string(),
                    text: "저두 다 가고싶긴 한데, 음악 학원이 있어서 힘들 것 같아요..".to_string(),
                    character_emotion: Some("musubbutsinna".to_string()),
                    background: Some("gym".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("은하".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string(), "은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "혜진".to_string(),
                    text: "나도 학생회 일정이 좀 빡빡해서 힘들 것 같은데, 성헌이 넌?".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("gym".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("혜진".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string(), "은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "성헌".to_string(),
                    text: "전 당분간은 괜찮을 것 같아요, 학원 선생님들이 단체로 독감에 걸리셔서 당분간 온라인 강의로 대체됐거든요.".to_string(),
                    character_emotion: Some("".to_string()),
                    background: Some("gym".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("성헌".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string(), "은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "혜진".to_string(),
                    text: "그래? 그럼 성헌아 부탁할게.. 이번 일 끝나면 다같이 동아리 회비로 맛있는 거 먹으러가자, 돈 좀 오버되면 내가 낼게".to_string(),
                    character_emotion: Some("happy".to_string()),
                    background: Some("gym".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("혜진".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string(), "은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "은하".to_string(),
                    text: "좋아요! 오빠 잘 부탁드려요!".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("gym".to_string()), 
                    choices: None,
                    next_line_index: None,
                    displayed_character: Some("은하".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string(), "은하".to_string()]), // 혼자
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                },
                DialogueLine {
                    speaker: "하나".to_string(),
                    text: "그럼 박성헌이 너가 다 가야하니까, 다음에 어디부터 갈건지 너가 정해".to_string(),
                    character_emotion: Some("def".to_string()),
                    background: Some("gym".to_string()), 
                    displayed_character: Some("하나".to_string()),
                    visible_characters: Some(vec!["혜진".to_string(), "하나".to_string(), "은하".to_string()]),
                    event_image: None,
                    minigame_trigger: None,
                sound_effect: None,
                    next_line_index: None,
                    choices: Some(vec![
                        Choice {
                            text: "음악실".to_string(),
                            next_scene_id: Some("chapter1".to_string()),
                            next_line_index: None,
                            choice_id: "chapter1".to_string(),
                            affection_changes: None,
                        },
                        Choice {
                            text: "옥상".to_string(),
                            next_scene_id: Some("chapter2".to_string()),
                            next_line_index: None,
                            choice_id: "chapter2".to_string(),
                            affection_changes: None,
                        },
                        Choice {
                            text: "도서관".to_string(),
                            next_scene_id: Some("chapter3".to_string()),
                            next_line_index: None,
                            choice_id: "chapter3".to_string(),
                            affection_changes: None,
                        },
                    ]),
                //게임 창 띄우고 스타트 버튼도 띄움 버튼 보여주고 그거대로 누르기 한 몇라운드 진행하면 될 듯
            }],
        }
}