use super::{DialogueLine, DialogueScene};
use crate::dialogue::Choice;
// Import the Choice struct if it exists in the parent module

pub fn create_s_hana() -> DialogueScene {
    DialogueScene {
        scene_id: "s_hana".to_string(),
        background: Some("science_2".to_string()),
        lines: vec![
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "좋아, 아무래도 하나랑 같이 가면 편하게 할 수 있을 것 같아.".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("room".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["성헌".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "연락 남겼으니까. 내일 과학실로 가면 되겠다.".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("room".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["성헌".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "나레이션".to_string(),
                text: "다음날 점심시간, 과학실".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["성헌".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "여기가 마지막인거지? 바쁜 내가 도와주러 왔으니까 사례는 두둑히 하도록.".to_string(),
                character_emotion: Some("musi".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "당연하지, 다음에 뭐 별이나 보러갈까?".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine { // check
                speaker: "하나".to_string(),
                text: "야, 장난해? 옛날 취미라고 했잖아!".to_string(),
                character_emotion: Some("hwana".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "ㅠㅠ 왜 화를 내고 그래, 그냥 내가 보러가고 싶어서 그랬지~".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "에이 관둬, 열쇠나 마저 찾자.".to_string(),
                character_emotion: Some("hansim".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "그래그래, 하나 너도 물리 수업 들었던가?".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "응 그치? 너나 나나 이과잖아".to_string(),
                character_emotion: Some("hwana".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "그럼 여기도 많이 왔겠네, 난 아무리 생각해도 의심가는 곳이 없거든? 넌 생각나는 곳 없어?".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "하, 글쎄다. 나도 어제 너한테 연락받고 좀 생각해봤는데 전처럼 옥상이면 몰라도 과학실에선 늘 실험에 집중하니깐..".to_string(),
                character_emotion: Some("hansim".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "그건 맞지.. 진짜 너무 감이 안잡히네. 일단 계속 찾아보자..".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "좋아, 내가 교실 뒤쪽 찾고 너가 앞쪽 찾는걸로 하자.".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "분업 좋지, 오늘 하나 머리가 잘돌아가네? 밥을 맛있게 잘 먹었나본데?".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "야 진짜 뭐래.. 너때문에 매점에서 빵으로 대충 떼우고 나왔거든?".to_string(),
                character_emotion: Some("hwana".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "그니까 제대로 보상하지 않으면 진짜 가만 안둔다".to_string(),
                character_emotion: Some("buggu".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "....".to_string(),
                character_emotion: Some("hansim".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "야.. 근데 그 전에 옥상에서 했던 얘기....".to_string(),
                character_emotion: Some("buggu".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "어 잠만잠만 야 하나야 이거.. 이거 같은데?".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "근데 방금 뭐라고?".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "어? 아니 아니 됐어 아무말도 안했어. 그래서 뭐 찾았다고?".to_string(),
                character_emotion: Some("musub".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "아 여기, 여기에 지금껏 찾은 느낌의 쪽지를 찾아서, 한번 열어볼게.".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "\'컴퓨터를 키고 math.exe를 실행하시오.\'라는데? 찾던게 맞았나봐".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "math.exe? 흠 어디보자 아 찾았다. 이거같은데?".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "이것도 세번 하니까 감이 잡히네, 수학 문제 나오나보다.".to_string(),
                character_emotion: Some("hwana".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "그러게 ㅋㅋ 난 이제 다섯번째라 슬슬 질릴정도야 ㅋㅋㅋ 이번에도 후딱 끝내보자!".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                sound_effect: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: Some("math".to_string()),
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "하 마지막 문제만 좀 까다로웠네. 그래도 이 정도도 못 풀 내가 아니긴 해~".to_string(),
                character_emotion: Some("musi".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "그래서 아까 진짜 아무말도 안한거 맞아? 나 진짜 말 끊으려던게 아니였어서".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "어? 아 아니 그냥...그때 옥상에서 내 얘기 들어줘서 고맙다고...".to_string(),
                character_emotion: Some("buggu".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "그냥 별자리 공부 포기한게 좀 미련이 남았어서 좀 징얼댄거같은데, 너가 들어줘서 좀 괜찮았어".to_string(),
                character_emotion: Some("hwana".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "그런걸로 고맙긴, 난 오히려 하나 너랑 그런 진지한 대화 한거 처음이라서 더 좋았는데 뭐".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "아 몰라...그냥 이 얘기가 하고싶었어.".to_string(),
                character_emotion: Some("hansim".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "어 잠깐 하나야 조심해!!".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: Some("glass.ogg".to_string()),
            },
            //쨍그랑 소리
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: Some("hana2".to_string()),
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "꺅! 왜.. 왜 갑자기 말도 없이 끌어당겨.! 이건 또 왜 떨어지는거고..!!".to_string(),
                character_emotion: Some("buggu".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "아 미안해, 다칠까봐.. 좀 쎄게 당겨버렸네.. 괜찮아?".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "하 어어.. 다친 곳은 없어.. 하 미안 놀라서..".to_string(),
                character_emotion: Some("musub".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "아까 쪽지 찾다가 살짝 건드렸는데, 그래서 떨어졌나봐.. 미안해".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "됐어.! 뭘 사과를 해 오히려 니가 구해줬으면서.".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "근데..다음부턴.. 너무 갑자기 끌어당기지 마.. 놀랐잖아.!!".to_string(),
                character_emotion: Some("buggu".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "그치만 말하고 끌어당길 시간이 없었는데...".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "하나".to_string(),
                text: "시끄러워! 단톡방에 찾았다고 올리기나 해.!!".to_string(),
                character_emotion: Some("buggu".to_string()),
                background: Some("science_2".to_string()),
                choices: Some(vec![  // 선택지 추가
                    Choice {
                        text: "ㅋㅋㅋㅋㅋ 알았어. 그럼 수업 다 끝나고 이따 보자".to_string(),
                        next_scene_id: Some("end_0".to_string()),
                        next_line_index: None,
                        choice_id: "end_0".to_string(),
                        affection_changes: None,
                    },
                ]),
                next_line_index: None,
                displayed_character: Some("하나".to_string()),
                visible_characters: Some(vec!["하나".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
        ],
    }
}