use super::{DialogueLine, DialogueScene};
use crate::dialogue::Choice;

pub fn create_s_hjin() -> DialogueScene {
    DialogueScene {
        scene_id: "s_hjin".to_string(),
        background: Some("science_2".to_string()),
        lines: vec![
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "좋아, 아무래도 혜진 선배랑 같이 가면 많이 도와주실 것 같아.".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("room".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["성헌".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "연락 남겼으니까. 내일 과학실로 가면 되겠다.".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("room".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["성헌".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "나레이션".to_string(),
                text: "다음날 오후, 과학실".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["성헌".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "안녕 성헌아, 먼저 와있었네?".to_string(),
                character_emotion: Some("jinji".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "그럼요. 선배가 오시는데 제가 늦을수가 있나요?".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "오 뭐야~ 저번에 많이 배우겠다더니, 확실하게 배웠네?".to_string(),
                character_emotion: Some("happy".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine { // check
                speaker: "성헌".to_string(),
                text: "그럼요, 제가 누구 후밴데요!".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "맞지, 이제 걱정 안해도 되겠다. 안심이 되네".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "그건 좀 속상한데요. 제 걱정은 계속 해주시면 안돼요?".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "하하 성헌이 걱정이야 늘 하지, 내가 말한건 동아리 걱정이였어~ 서운했어?".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "그런거죠? 그럼 다행이네요 ㅋㅋㅋ".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "흠~ 그나저나 성헌이는 선택과목이 물리였지? 과학실엔 자주 왔겠네~".to_string(),
                character_emotion: Some("gomin".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "맞아요, 최근까지도 계속 실험 때문에 왔다갔다 했었어요. 근데 아무리 생각해도 위화감 있던건.....".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "....아! 있다..!".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "응? 뭐야 벌써 생각났어? 생각보다 빨리 끝나겠는걸?".to_string(),
                character_emotion: Some("jinji".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "그러게요, 좀 아쉬운데 그냥 기억 못한걸로 할까요?".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "그게 뭐야 ㅋㅋㅋㅋ 그럼 열쇠부터 얻고 대화나 조금 더 하다 갈까?".to_string(),
                character_emotion: Some("happy".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "좋아요, 제가 원했던 제안이네요 ㅋㅋㅋ".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "그럼 떠오르신 곳으로 인도해주실래요? 후배님?".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine { // check
                speaker: "성헌".to_string(),
                text: "네 선배님 저만 따라오시죠~".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "전에 한번 선생님이 시키셔서 모니터를 키러 갔다가 뭔가 쪽지같은걸 본 기억이 있거든요? 쓰레긴 줄 알고 무시하긴 했지만요.".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "그래? 그럼 일단 그것부터 열어보자".to_string(),
                character_emotion: Some("jinji".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "여깄다. \'컴퓨터를 키고 math.exe를 실행하세요.\'라고 적혀있네요?".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "음... math.exe~..".to_string(),
                character_emotion: Some("jinji".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "아! 찾았다. 이건가봐".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "그럼 한번 마지막 난관을 해치워볼까요?".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                sound_effect: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: Some("math".to_string()),
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "성공이네! 성헌아 고생 많았어, 역시 우리 동아리 에이스던데?".to_string(),
                character_emotion: Some("happy".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "이게 다 훌륭한 선배님 밑에서 배운 실력이 아닐까 싶네요~ 스승을 잘둔거죠.".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "역시.. 아부도 잘 배웠네!".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "아부라뇨 진심인데요..".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "그럼 아까 얘기한대로 좀만 더 얘기하다가 갈까?".to_string(),
                character_emotion: Some("happy".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "좋아요. 마침 해질녘이라 노을이 예쁘던데, 창가쪽으로 갈까요?".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "좋은 생각인데? 그래서 우리 후배님이 나랑 무슨 대화가 하고싶었을까?".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "그, 전에 선배 그거요..그거.. 그때 하신 말, 무슨 의미에요?".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "아 그때 그거? 음 그건..".to_string(),
                character_emotion: Some("gomin".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "엇, 바람이..".to_string(),
                character_emotion: Some("ariyon".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "앗 잠시만요 제가..".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: Some("Hjin2".to_string()),
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "......무슨 의미일진 스스로 생각해보는걸로!".to_string(),
                character_emotion: Some("happy".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "네? 또요? 너무해요.! 대체 언제 알려주시려고요..!".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "음~ 글쎄? 나도 잘 모르겠네".to_string(),
                character_emotion: Some("gomin".to_string()),
                background: Some("science_2".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "혜진".to_string(),
                text: "좋아! 이제 마지막 열쇠를 가지고 구관으로 돌아가볼까?".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("science_2".to_string()),
                choices: Some(vec![  // 선택지 추가
                    Choice {
                        text: "좋아요.. 일단 그럼 제가 카톡방에 연락할게요.".to_string(),
                        next_scene_id: Some("end_0".to_string()),
                        next_line_index: None,
                        choice_id: "end_0".to_string(),
                        affection_changes: None,
                    },
                ]),
                next_line_index: None,
                displayed_character: Some("혜진".to_string()),
                visible_characters: Some(vec!["혜진".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
        ],
    }
}