use super::{DialogueLine, DialogueScene};
use crate::dialogue::Choice;
// Import the Choice struct if it exists in the parent module

pub fn create_s_unha() -> DialogueScene {
    DialogueScene {
        scene_id: "s_unha".to_string(),
        background: Some("science_1".to_string()),
        lines: vec![
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "좋아, 아무래도 은하랑 같이 가면 재밌을 것 같아.".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("room".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["성헌".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "연락 남겼으니까. 내일 과학실로 가면 되겠다.".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("room".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["성헌".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "나레이션".to_string(),
                text: "다음날 오전, 과학실".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("science_1".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["성헌".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "우와.. 과학실을 이렇게 이른 아침에 오는건 처음이네요!".to_string(),
                character_emotion: Some("banjjack".to_string()),
                background: Some("science_1".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "그러네, 미안해 너무 아침 일찍 불렀지? 저녁엔 과학 동아리 실험이 있다고 해서..".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_1".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "괜찮아요! 원래 이시간대 일어나서 미리 음악실에 가있거든요!".to_string(),
                character_emotion: Some("sinna".to_string()),
                background: Some("science_1".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "그래도.. 피아노 연습시간 뺏은 느낌이라 미안해서".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_1".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "괜찮대두요~ 정 미안하면 다음에 오빠가 음악실 한번 놀러와주세요!".to_string(),
                character_emotion: Some("buggu".to_string()),
                background: Some("science_1".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "ㅋㅋㅋ 그래 좋아 그정도는 평소에도 할 수 있겠는데?".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_1".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "그나저나 과학실은 신기한게 많네요...".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("science_1".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "음? 은하는 과학실 많이 안와봤어?".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_1".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "아직 실험실에서 하는 수업이 많이 없어서, 몇번 와보긴 했는데 이렇게 자세히 본 적은 없어요!".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("science_1".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "아 그렇겠네, 과학실은 위험하니까 조심해서 둘러보자".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_1".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "네 좋아요! 근데 오빠는 되게 잘 아는 것 같은데, 2학년땐 실험실 쓸 일이 많아요?".to_string(),
                character_emotion: Some("def".to_string()),
                background: Some("science_1".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "음 내가 아무래도 선택과목이 물리여서, 실험하러 자주 오거든".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_1".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "하....저는 과학같은건 너무너무 싫어요..아무래도 전 문과쪽으로 선택해야할 것 같아요..".to_string(),
                character_emotion: Some("musub".to_string()),
                background: Some("science_1".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "에이 그래도 물리 한번 해봐, 내가 과외해줄게!".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_1".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "우와! 진짜요? 저 기억할게요! 오빠 잊으시면 안돼요!".to_string(),
                character_emotion: Some("banjjack".to_string()),
                background: Some("science_1".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "어 잠만 은하야, 여기 이거 같은데? 모니터 뒤쪽에 쪽지가 껴있어.".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_1".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "\'컴퓨터를 키고 math.exe를 실행하세요.\'라고 적혀있네?".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_1".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "으으음 여기있다! 선배 제가 찾았어요!".to_string(),
                character_emotion: Some("sinna".to_string()),
                background: Some("science_1".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "좋아 그럼 이제 해볼까? 제목 보니까 수학 문젠가봐".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_1".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "으..수학이요..? 너무 싫은데.. 저 오빠만 믿을게요..".to_string(),
                character_emotion: Some("musubbutsinna".to_string()),
                background: Some("science_1".to_string()),
                choices: None,
                next_line_index: None,
                sound_effect: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: Some("math".to_string()),
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "후! 마지막 문제 말고는 꽤 할만했네?".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_1".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "으.. 저는 오빠 없었으면 하고싶지 않았을 것 같아요..".to_string(),
                character_emotion: Some("musub".to_string()),
                background: Some("science_1".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "ㅋㅋㅋ 왜 잘하던데!".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_1".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "도움이 된거 맞죠..?".to_string(),
                character_emotion: Some("musubbutsinna".to_string()),
                background: Some("science_1".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "당연하지! 은하랑 같이 있으면 얼마나 많이 도움이 되는데~".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_1".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "헤헤.. 오빠한테 도움 될 수 있어서 다행이에요!".to_string(),
                character_emotion: Some("buggu".to_string()),
                background: Some("science_1".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "꺅..! 어..자 잠만 이거 갑자기 왜 불이..!".to_string(),
                character_emotion: Some("musub".to_string()),
                background: Some("science_3".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "괜찮아, 괜찮아. 그냥 잠깐 꺼졌다가 괜찮아질거야.".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_3".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_3".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: Some("unha2".to_string()),
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "죄..죄송해요..! 너무 놀라서..!".to_string(),
                character_emotion: Some("buggu".to_string()),
                background: Some("science_3".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "아냐 진짜 놀랄만 했는데 뭘, 이제 좀 괜찮아? 아직 불이 안들어오네.".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_3".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "하.. 좀 괜찮은 것 같아요.! 갑자기 꺼져서 조금 놀랐네요..!!".to_string(),
                character_emotion: Some("musubbutsinna".to_string()),
                background: Some("science_3".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "엇 불 켜졌다. 다행히 생각보다 금방 돌아왔네".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_1".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "오빠가 있어서.. 다행인 것 같아요.. 정말...".to_string(),
                character_emotion: Some("buggu".to_string()),
                background: Some("science_1".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "은하가 너무 깜짝 놀라서 오히려 내가 안놀랐네 ㅋㅋ 재밌는 경험도 하고 완전 스펙타클한 모험이네!".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_1".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "오! 그렇게 생각하니까 진짜 좀 두근거리네요.!!".to_string(),
                character_emotion: Some("banjjack".to_string()),
                background: Some("science_1".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "성헌".to_string(),
                text: "역시 은하는 긍정적이라 좋다! 이제 슬슬 동아리 톡방에 연락 남겨두자.".to_string(),
                character_emotion: Some("".to_string()),
                background: Some("science_1".to_string()),
                choices: None,
                next_line_index: None,
                displayed_character: Some("성헌".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
            DialogueLine {
                speaker: "은하".to_string(),
                text: "넹! 그럼 방과후에 다시 만나요! 오빠!".to_string(),
                character_emotion: Some("sinna".to_string()),
                background: Some("science_1".to_string()),
                choices: Some(vec![  // 선택지 추가
                    Choice {
                        text: "그래 은하도 수업 잘 듣고 이따보자!".to_string(),
                        next_scene_id: Some("end_0".to_string()),
                        next_line_index: None,
                        choice_id: "end_0".to_string(),
                        affection_changes: None,
                    },
                ]),
                next_line_index: None,
                displayed_character: Some("은하".to_string()),
                visible_characters: Some(vec!["은하".to_string()]),
                event_image: None,
                minigame_trigger: None,
                sound_effect: None,
            },
        ],
    }
}